/**
 * Strings for measurement, location and the field report, in the four
 * supported languages. Merged into DICT by i18n-dict.ts; English is the
 * fallback for any missing key.
 */

export const DOC_DICT: Record<string, Record<string, string>> = {
  en: {
    /* 360 viewer */
    "pv.title": "360° viewer",
    "pv.intro": "Open a 360° photograph, look around it, and mark points on the walls.",
    "pv.load": "Open a 360° photograph",
    "pv.empty": "No panorama open",
    "pv.unreadable": "That image could not be read.",
    "pv.notEquirect":
      "This does not look like a 360° photograph — those are twice as wide as they are tall. It will be shown, but it will look stretched.",
    "pv.zoomIn": "Zoom in",
    "pv.zoomOut": "Zoom out",
    "pv.recentre": "Recentre",
    "pv.points": "Information points",
    "pv.pointLabel": "What is here",
    "pv.tapToPlace": "Tap the spot in the image.",
    "pv.removePoint": "Remove point",
    "pv.caveat":
      "A viewer, not a stitcher: it opens a finished 360° photograph from a panoramic camera or your phone's panorama mode. Points are kept for this session only.",
    /* search, sites, outbox */
    "sr.placeholder": "Search projects, readings, notes",
    "sr.hint": "Diacritics are ignored: type “hdr” to find “ḥḏr”, “محمد” to find “مُحَمَّد”.",
    "sr.results": "{count} of {total}",
    "sr.none": "Nothing matched that.",
    "sr.clear": "Clear search",
    "st.title": "Sites",
    "st.count": "{sites} site(s) from {located} located record(s)",
    "st.spread": "spread {m} m",
    "st.exportGeojson": "Export GeoJSON (QGIS)",
    "st.exportCsv": "Export CSV",
    "st.none": "No project has a recorded position yet.",
    "ob.title": "Waiting to send",
    "ob.pending": "{count} item(s) queued",
    "ob.retryAll": "Try now",
    "ob.retry": "Retry",
    "ob.discard": "Discard",
    "ob.stalled": "Stopped after several failed attempts.",
    "ob.queued": "No connection — queued. It will send itself when the signal returns.",
    "ob.sent": "{count} queued item(s) sent.",
    "ob.rejected": "“{label}” was rejected and removed: {error}",
    /* offline / install */
    "pwa.offline": "No connection.",
    "pwa.offlineWhatWorks":
      "Your saved projects, enhancement, measurement and writing all still work. Reading and 3D reconstruction resume when the signal returns.",
    "pwa.updateReady": "A new version of Athar is ready.",
    "pwa.updateNow": "Update",
    /* measurement */
    "ms.title": "Measure",
    "ms.intro":
      "Measurements are taken against an object of known length in the photograph. Place the scale first, then measure.",
    "ms.setScale": "Set the scale",
    "ms.scaleHint": "Drag along an object whose true length you know.",
    "ms.scaleSet": "Scale: {label} = {mm} mm",
    "ms.knownLength": "True length (mm)",
    "ms.refLabel": "What it is",
    "ms.ref.scale10": "10 cm scale bar",
    "ms.ref.scale5": "5 cm scale bar",
    "ms.ref.scale20": "20 cm scale bar",
    "ms.ref.a4long": "A4 sheet, long edge",
    "ms.ref.creditCard": "Bank card, long edge",
    "ms.ref.custom": "Something else",
    "ms.tool.length": "Length",
    "ms.tool.path": "Path",
    "ms.tool.area": "Area",
    "ms.addMeasurement": "Add measurement",
    "ms.finish": "Finish shape",
    "ms.undo": "Undo last point",
    "ms.clear": "Clear all",
    "ms.remove": "Remove",
    "ms.nameIt": "Name this measurement",
    "ms.noScale": "Set the scale first — without it these are pixels, not millimetres.",
    "ms.weakScale":
      "That reference is small in the frame, so every measurement carries about {percent}% uncertainty. Use a longer one if you can.",
    "ms.caveat":
      "Valid only for a flat surface photographed square-on, with the scale on the same plane as what is measured. Depth and height cannot be recovered from one photograph.",
    "ms.extent": "Extent (width × height)",
    "ms.saved": "Measurements saved with the project.",
    /* location */
    "geo.title": "Findspot",
    "geo.capture": "Record this position",
    "geo.recording": "Reading the satellites…",
    "geo.accuracy": "Accurate to about {m} m",
    "geo.weak":
      "This fix is only accurate to about {m} m, which may fall outside the feature itself. Wait in the open for a better one.",
    "geo.openMap": "Open in a map",
    "geo.clear": "Remove the position",
    "geo.denied":
      "Location permission was refused. Allow it in your browser settings to record a findspot.",
    "geo.unsupported": "This browser cannot read a position.",
    "geo.timeout": "No position yet. Under open sky it usually takes a few seconds longer.",
    "geo.unavailable": "The position could not be read.",
    "geo.privacy":
      "Stored on this device with the project. It is never sent anywhere on its own, and it is left out of a shared report unless you include it.",
    /* report */
    "rp.title": "Field report",
    "rp.build": "Create report (PDF)",
    "rp.building": "Preparing the report…",
    "rp.hint": "Opens your print dialog — choose “Save as PDF”.",
    "rp.includeLocation": "Include the findspot coordinates",
    "rp.failed": "The report could not be prepared.",
    "rp.h.recordedOn": "Recorded",
    "rp.h.notes": "Notes",
    "rp.h.photographs": "Photographs",
    "rp.h.original": "As photographed",
    "rp.h.enhanced": "Processed",
    "rp.h.processingNote":
      "Processed colours are the output of pixel operations (decorrelation stretch or CLAHE). They are false colour and are not the pigment or stone colour.",
    "rp.h.location": "Findspot",
    "rp.h.coordinates": "Coordinates",
    "rp.h.accuracyLabel": "Accuracy",
    "rp.h.altitude": "Altitude",
    "rp.h.locationWithheld": "The coordinates were deliberately left out of this report.",
    "rp.h.measurements": "Measurements",
    "rp.h.scaleReference": "Scale reference",
    "rp.h.reading": "Suggested reading",
    "rp.h.script": "Script",
    "rp.h.direction": "Direction",
    "rp.h.transliteration": "Transliteration",
    "rp.h.proposedReading": "Proposed reading",
    "rp.h.meaning": "Meaning",
    "rp.h.uncertainties": "Uncertain",
    "rp.h.alternatives": "Alternatives",
    "rp.h.machineCaveat":
      "A machine suggestion, not an established reading. It has not been checked by an epigrapher and must not be cited as a decipherment.",
    "rp.h.corrections": "Corrections by the recorder",
    "rp.h.references": "Sources consulted",
    "rp.h.page": "Produced with Athar. Readings are machine suggestions requiring expert review.",
  },

  ar: {
    "pv.title": "عارض ٣٦٠°",
    "pv.intro": "افتح صورة ٣٦٠°، وتجوّل داخلها، وضع نقاطًا على الجدران.",
    "pv.load": "افتح صورة ٣٦٠°",
    "pv.empty": "لا توجد صورة بانورامية مفتوحة",
    "pv.unreadable": "تعذّرت قراءة هذه الصورة.",
    "pv.notEquirect":
      "هذه لا تبدو صورة ٣٦٠° — عرضها يجب أن يكون ضعف ارتفاعها. ستُعرض، لكنها ستبدو ممطوطة.",
    "pv.zoomIn": "تقريب",
    "pv.zoomOut": "تبعيد",
    "pv.recentre": "إعادة التوسيط",
    "pv.points": "نقاط المعلومات",
    "pv.pointLabel": "ما الموجود هنا",
    "pv.tapToPlace": "انقر الموضع داخل الصورة.",
    "pv.removePoint": "حذف النقطة",
    "pv.caveat":
      "عارض لا مُجمِّع: يفتح صورة ٣٦٠° جاهزة من كاميرا بانورامية أو من وضع البانوراما في هاتفك. النقاط تُحفظ لهذه الجلسة فقط.",
    "sr.placeholder": "ابحث في المشاريع والقراءات والملاحظات",
    "sr.hint": "التشكيل مُتجاهَل: اكتب «hdr» لتجد «ḥḏr»، و«محمد» لتجد «مُحَمَّد».",
    "sr.results": "{count} من {total}",
    "sr.none": "لا نتائج مطابقة.",
    "sr.clear": "مسح البحث",
    "st.title": "المواقع",
    "st.count": "{sites} موقعًا من {located} سجلًا محدَّد الموضع",
    "st.spread": "امتداد {m} متر",
    "st.exportGeojson": "تصدير GeoJSON لـQGIS",
    "st.exportCsv": "تصدير CSV",
    "st.none": "لا يوجد مشروع بموضع مسجَّل بعد.",
    "ob.title": "في انتظار الإرسال",
    "ob.pending": "{count} عنصرًا في الطابور",
    "ob.retryAll": "حاول الآن",
    "ob.retry": "إعادة المحاولة",
    "ob.discard": "تجاهل",
    "ob.stalled": "توقّف بعد عدة محاولات فاشلة.",
    "ob.queued": "لا يوجد اتصال — أُضيف إلى الطابور وسيُرسَل تلقائيًا عند عودة الشبكة.",
    "ob.sent": "أُرسل {count} عنصرًا من الطابور.",
    "ob.rejected": "رُفض «{label}» وأُزيل: {error}",
    "pwa.offline": "لا يوجد اتصال.",
    "pwa.offlineWhatWorks":
      "مشاريعك المحفوظة والتحسين والقياس والكتابة كلها تعمل. القراءة وإعادة البناء ثلاثي الأبعاد تستأنفان عند عودة الشبكة.",
    "pwa.updateReady": "تتوفر نسخة جديدة من «أثر».",
    "pwa.updateNow": "تحديث",
    "ms.title": "القياس",
    "ms.intro":
      "يُقاس بالاستناد إلى جسم معلوم الطول داخل الصورة. حدّد المقياس أولًا ثم ابدأ القياس.",
    "ms.setScale": "تحديد المقياس",
    "ms.scaleHint": "اسحب على طول جسم تعرف طوله الحقيقي.",
    "ms.scaleSet": "المقياس: {label} = {mm} مم",
    "ms.knownLength": "الطول الحقيقي (مم)",
    "ms.refLabel": "ما هو المرجع",
    "ms.ref.scale10": "مسطرة قياس ١٠ سم",
    "ms.ref.scale5": "مسطرة قياس ٥ سم",
    "ms.ref.scale20": "مسطرة قياس ٢٠ سم",
    "ms.ref.a4long": "ورقة A4، الضلع الطويل",
    "ms.ref.creditCard": "بطاقة بنكية، الضلع الطويل",
    "ms.ref.custom": "شيء آخر",
    "ms.tool.length": "طول",
    "ms.tool.path": "مسار",
    "ms.tool.area": "مساحة",
    "ms.addMeasurement": "إضافة قياس",
    "ms.finish": "إنهاء الشكل",
    "ms.undo": "تراجع عن آخر نقطة",
    "ms.clear": "مسح الكل",
    "ms.remove": "حذف",
    "ms.nameIt": "سمِّ هذا القياس",
    "ms.noScale": "حدّد المقياس أولًا — بدونه هذه بكسلات لا مليمترات.",
    "ms.weakScale":
      "المرجع صغير داخل الإطار، لذا يحمل كل قياس عدم يقين يقارب {percent}٪. استخدم مرجعًا أطول إن أمكن.",
    "ms.caveat":
      "صالح فقط لسطح مستوٍ صُوِّر بشكل عمودي، والمقياس على المستوى نفسه للمقاس. العمق والارتفاع لا يُستخرجان من صورة واحدة.",
    "ms.extent": "الامتداد (عرض × ارتفاع)",
    "ms.saved": "حُفظت القياسات مع المشروع.",
    "geo.title": "موقع الاكتشاف",
    "geo.capture": "تسجيل هذا الموقع",
    "geo.recording": "جارٍ قراءة الأقمار الصناعية…",
    "geo.accuracy": "الدقة نحو {m} متر",
    "geo.weak":
      "دقة هذا التحديد نحو {m} متر، وقد يقع خارج المَعلم نفسه. انتظر في مكان مكشوف للحصول على تحديد أدق.",
    "geo.openMap": "فتح في الخريطة",
    "geo.clear": "إزالة الموقع",
    "geo.denied": "رُفض إذن الموقع. اسمح به في إعدادات المتصفح لتسجيل موقع الاكتشاف.",
    "geo.unsupported": "هذا المتصفح لا يستطيع قراءة الموقع.",
    "geo.timeout": "لا يوجد تحديد بعد. تحت السماء المكشوفة يستغرق الأمر ثوانٍ إضافية عادةً.",
    "geo.unavailable": "تعذّرت قراءة الموقع.",
    "geo.privacy":
      "يُحفظ على هذا الجهاز مع المشروع. لا يُرسل إلى أي جهة بمفرده، ويُستبعد من التقرير المُشارَك ما لم تُدرجه بنفسك.",
    "rp.title": "التقرير الميداني",
    "rp.build": "إنشاء تقرير (PDF)",
    "rp.building": "جارٍ تجهيز التقرير…",
    "rp.hint": "يفتح نافذة الطباعة — اختر «حفظ بصيغة PDF».",
    "rp.includeLocation": "تضمين إحداثيات موقع الاكتشاف",
    "rp.failed": "تعذّر تجهيز التقرير.",
    "rp.h.recordedOn": "سُجِّل في",
    "rp.h.notes": "ملاحظات",
    "rp.h.photographs": "الصور",
    "rp.h.original": "كما صُوِّرت",
    "rp.h.enhanced": "بعد المعالجة",
    "rp.h.processingNote":
      "ألوان الصورة المعالَجة ناتج عمليات على البكسل (decorrelation stretch أو CLAHE). هي ألوان زائفة وليست لون الصبغة أو الحجر.",
    "rp.h.location": "موقع الاكتشاف",
    "rp.h.coordinates": "الإحداثيات",
    "rp.h.accuracyLabel": "الدقة",
    "rp.h.altitude": "الارتفاع",
    "rp.h.locationWithheld": "حُذفت الإحداثيات من هذا التقرير عمدًا.",
    "rp.h.measurements": "القياسات",
    "rp.h.scaleReference": "مرجع المقياس",
    "rp.h.reading": "القراءة المقترحة",
    "rp.h.script": "الخط",
    "rp.h.direction": "الاتجاه",
    "rp.h.transliteration": "النقحرة",
    "rp.h.proposedReading": "القراءة المقترحة",
    "rp.h.meaning": "المعنى",
    "rp.h.uncertainties": "مواضع الشك",
    "rp.h.alternatives": "قراءات بديلة",
    "rp.h.machineCaveat":
      "اقتراح آلي وليس قراءة مُثبتة. لم يراجعه مختص في النقوش، ولا يجوز الاستشهاد به بوصفه فكًّا للنقش.",
    "rp.h.corrections": "تصويبات المُسجِّل",
    "rp.h.references": "المصادر المرجوعة",
    "rp.h.page": "أُنتج بواسطة «أثر». القراءات اقتراحات آلية تتطلب مراجعة مختص.",
  },

  fr: {
    "pv.title": "Visionneuse 360°",
    "pv.intro":
      "Ouvrez une photographie 360°, regardez autour de vous et marquez des points sur les parois.",
    "pv.load": "Ouvrir une photographie 360°",
    "pv.empty": "Aucun panorama ouvert",
    "pv.unreadable": "Cette image n’a pas pu être lue.",
    "pv.notEquirect":
      "Cela ne ressemble pas à une photographie 360° — celles-ci sont deux fois plus larges que hautes. Elle sera affichée, mais étirée.",
    "pv.zoomIn": "Zoom avant",
    "pv.zoomOut": "Zoom arrière",
    "pv.recentre": "Recentrer",
    "pv.points": "Points d’information",
    "pv.pointLabel": "Ce qui se trouve ici",
    "pv.tapToPlace": "Touchez l’endroit sur l’image.",
    "pv.removePoint": "Supprimer le point",
    "pv.caveat":
      "Une visionneuse, pas un assembleur : elle ouvre une photographie 360° déjà produite par une caméra panoramique ou le mode panorama du téléphone. Les points ne durent que le temps de la session.",
    "sr.placeholder": "Rechercher projets, lectures, notes",
    "sr.hint": "Les signes diacritiques sont ignorés : tapez « hdr » pour trouver « ḥḏr ».",
    "sr.results": "{count} sur {total}",
    "sr.none": "Aucun résultat.",
    "sr.clear": "Effacer la recherche",
    "st.title": "Sites",
    "st.count": "{sites} site(s) à partir de {located} enregistrement(s) localisé(s)",
    "st.spread": "étendue {m} m",
    "st.exportGeojson": "Exporter en GeoJSON (QGIS)",
    "st.exportCsv": "Exporter en CSV",
    "st.none": "Aucun projet n’a encore de position enregistrée.",
    "ob.title": "En attente d’envoi",
    "ob.pending": "{count} élément(s) en file",
    "ob.retryAll": "Essayer maintenant",
    "ob.retry": "Réessayer",
    "ob.discard": "Abandonner",
    "ob.stalled": "Arrêté après plusieurs tentatives infructueuses.",
    "ob.queued": "Aucune connexion — mis en file. L’envoi se fera au retour du signal.",
    "ob.sent": "{count} élément(s) en file envoyé(s).",
    "ob.rejected": "« {label} » a été rejeté et retiré : {error}",
    "pwa.offline": "Aucune connexion.",
    "pwa.offlineWhatWorks":
      "Vos projets enregistrés, le traitement, les mesures et l’écriture fonctionnent toujours. La lecture et la reconstruction 3D reprendront au retour du signal.",
    "pwa.updateReady": "Une nouvelle version d’Athar est prête.",
    "pwa.updateNow": "Mettre à jour",
    "ms.title": "Mesurer",
    "ms.intro":
      "Les mesures se prennent par rapport à un objet de longueur connue présent sur la photographie. Définissez d’abord l’échelle.",
    "ms.setScale": "Définir l’échelle",
    "ms.scaleHint": "Tracez le long d’un objet dont vous connaissez la longueur réelle.",
    "ms.scaleSet": "Échelle : {label} = {mm} mm",
    "ms.knownLength": "Longueur réelle (mm)",
    "ms.refLabel": "Nature de la référence",
    "ms.ref.scale10": "Mire de 10 cm",
    "ms.ref.scale5": "Mire de 5 cm",
    "ms.ref.scale20": "Mire de 20 cm",
    "ms.ref.a4long": "Feuille A4, grand côté",
    "ms.ref.creditCard": "Carte bancaire, grand côté",
    "ms.ref.custom": "Autre chose",
    "ms.tool.length": "Longueur",
    "ms.tool.path": "Tracé",
    "ms.tool.area": "Surface",
    "ms.addMeasurement": "Ajouter une mesure",
    "ms.finish": "Terminer la forme",
    "ms.undo": "Annuler le dernier point",
    "ms.clear": "Tout effacer",
    "ms.remove": "Supprimer",
    "ms.nameIt": "Nommer cette mesure",
    "ms.noScale":
      "Définissez d’abord l’échelle — sans elle ce sont des pixels, pas des millimètres.",
    "ms.weakScale":
      "Cette référence est petite dans le cadre : chaque mesure porte environ {percent} % d’incertitude. Utilisez-en une plus longue si possible.",
    "ms.caveat":
      "Valable uniquement pour une surface plane photographiée de face, l’échelle reposant sur le même plan que l’objet mesuré. La profondeur ne se déduit pas d’une seule photographie.",
    "ms.extent": "Emprise (largeur × hauteur)",
    "ms.saved": "Mesures enregistrées avec le projet.",
    "geo.title": "Lieu de découverte",
    "geo.capture": "Enregistrer cette position",
    "geo.recording": "Lecture des satellites…",
    "geo.accuracy": "Précision d’environ {m} m",
    "geo.weak":
      "Cette position n’est précise qu’à environ {m} m et peut tomber hors du vestige. Attendez à découvert pour une meilleure lecture.",
    "geo.openMap": "Ouvrir dans une carte",
    "geo.clear": "Retirer la position",
    "geo.denied":
      "Autorisation de localisation refusée. Activez-la dans les réglages du navigateur.",
    "geo.unsupported": "Ce navigateur ne peut pas lire une position.",
    "geo.timeout":
      "Pas encore de position. À ciel ouvert, cela prend généralement quelques secondes de plus.",
    "geo.unavailable": "La position n’a pas pu être lue.",
    "geo.privacy":
      "Conservée sur cet appareil avec le projet. Elle n’est jamais transmise seule et reste exclue d’un rapport partagé sauf si vous l’incluez.",
    "rp.title": "Rapport de terrain",
    "rp.build": "Créer le rapport (PDF)",
    "rp.building": "Préparation du rapport…",
    "rp.hint": "Ouvre la fenêtre d’impression — choisissez « Enregistrer au format PDF ».",
    "rp.includeLocation": "Inclure les coordonnées du lieu",
    "rp.failed": "Le rapport n’a pas pu être préparé.",
    "rp.h.recordedOn": "Enregistré le",
    "rp.h.notes": "Notes",
    "rp.h.photographs": "Photographies",
    "rp.h.original": "Telle que photographiée",
    "rp.h.enhanced": "Après traitement",
    "rp.h.processingNote":
      "Les couleurs traitées résultent d’opérations sur les pixels (decorrelation stretch ou CLAHE). Ce sont de fausses couleurs, non celles du pigment ou de la pierre.",
    "rp.h.location": "Lieu de découverte",
    "rp.h.coordinates": "Coordonnées",
    "rp.h.accuracyLabel": "Précision",
    "rp.h.altitude": "Altitude",
    "rp.h.locationWithheld": "Les coordonnées ont été volontairement omises de ce rapport.",
    "rp.h.measurements": "Mesures",
    "rp.h.scaleReference": "Référence d’échelle",
    "rp.h.reading": "Lecture proposée",
    "rp.h.script": "Écriture",
    "rp.h.direction": "Sens",
    "rp.h.transliteration": "Translittération",
    "rp.h.proposedReading": "Lecture proposée",
    "rp.h.meaning": "Sens",
    "rp.h.uncertainties": "Incertitudes",
    "rp.h.alternatives": "Variantes",
    "rp.h.machineCaveat":
      "Suggestion automatique et non lecture établie. Elle n’a pas été vérifiée par un épigraphiste et ne doit pas être citée comme un déchiffrement.",
    "rp.h.corrections": "Corrections de l’enregistreur",
    "rp.h.references": "Sources consultées",
    "rp.h.page":
      "Produit avec Athar. Les lectures sont des suggestions automatiques à valider par un spécialiste.",
  },

  zh: {
    "pv.title": "360° 查看器",
    "pv.intro": "打开一张 360° 照片，环顾四周，并在岩壁上标注要点。",
    "pv.load": "打开 360° 照片",
    "pv.empty": "尚未打开全景图",
    "pv.unreadable": "无法读取该图像。",
    "pv.notEquirect": "这看起来不像 360° 照片——它们的宽度应为高度的两倍。仍会显示，但会被拉伸。",
    "pv.zoomIn": "放大",
    "pv.zoomOut": "缩小",
    "pv.recentre": "回到中心",
    "pv.points": "信息点",
    "pv.pointLabel": "此处是什么",
    "pv.tapToPlace": "点击图中的位置。",
    "pv.removePoint": "删除该点",
    "pv.caveat":
      "这是查看器而非拼接器：它打开由全景相机或手机全景模式生成的成品 360° 照片。标注点仅在本次会话中保留。",
    "sr.placeholder": "搜索项目、释读与备注",
    "sr.hint": "忽略附加符号：输入“hdr”即可找到“ḥḏr”。",
    "sr.results": "{count} / {total}",
    "sr.none": "没有匹配结果。",
    "sr.clear": "清除搜索",
    "st.title": "遗址",
    "st.count": "由 {located} 条定位记录归并为 {sites} 处遗址",
    "st.spread": "范围 {m} 米",
    "st.exportGeojson": "导出 GeoJSON（QGIS）",
    "st.exportCsv": "导出 CSV",
    "st.none": "尚无项目记录了位置。",
    "ob.title": "等待发送",
    "ob.pending": "队列中有 {count} 项",
    "ob.retryAll": "立即尝试",
    "ob.retry": "重试",
    "ob.discard": "丢弃",
    "ob.stalled": "多次尝试失败后已停止。",
    "ob.queued": "无网络连接——已加入队列，恢复信号后会自动发送。",
    "ob.sent": "已发送队列中的 {count} 项。",
    "ob.rejected": "“{label}”被拒绝并已移除：{error}",
    "pwa.offline": "无网络连接。",
    "pwa.offlineWhatWorks":
      "已保存的项目、图像处理、测量与书写均可继续使用。释读与三维重建将在恢复信号后继续。",
    "pwa.updateReady": "Athar 有新版本可用。",
    "pwa.updateNow": "更新",
    "ms.title": "测量",
    "ms.intro": "测量以照片中已知长度的物体为基准。请先设定比例尺，再进行测量。",
    "ms.setScale": "设定比例尺",
    "ms.scaleHint": "沿着一件你知道真实长度的物体拖动。",
    "ms.scaleSet": "比例尺：{label} = {mm} 毫米",
    "ms.knownLength": "真实长度（毫米）",
    "ms.refLabel": "参照物是什么",
    "ms.ref.scale10": "10 厘米比例尺",
    "ms.ref.scale5": "5 厘米比例尺",
    "ms.ref.scale20": "20 厘米比例尺",
    "ms.ref.a4long": "A4 纸长边",
    "ms.ref.creditCard": "银行卡长边",
    "ms.ref.custom": "其他",
    "ms.tool.length": "长度",
    "ms.tool.path": "路径",
    "ms.tool.area": "面积",
    "ms.addMeasurement": "添加测量",
    "ms.finish": "完成图形",
    "ms.undo": "撤销上一点",
    "ms.clear": "全部清除",
    "ms.remove": "删除",
    "ms.nameIt": "为此测量命名",
    "ms.noScale": "请先设定比例尺——否则这些只是像素，不是毫米。",
    "ms.weakScale":
      "该参照物在画面中偏小，每项测量约有 {percent}% 的不确定度。如可能请改用更长的参照物。",
    "ms.caveat":
      "仅适用于正对拍摄的平面，且比例尺与被测对象位于同一平面。单张照片无法还原深度与高度。",
    "ms.extent": "范围（宽 × 高）",
    "ms.saved": "测量已随项目保存。",
    "geo.title": "发现地点",
    "geo.capture": "记录当前位置",
    "geo.recording": "正在读取卫星信号…",
    "geo.accuracy": "精度约 {m} 米",
    "geo.weak": "此定位精度约 {m} 米，可能落在遗迹之外。请到开阔处等待更好的定位。",
    "geo.openMap": "在地图中打开",
    "geo.clear": "移除位置",
    "geo.denied": "位置权限被拒绝。请在浏览器设置中允许，以记录发现地点。",
    "geo.unsupported": "此浏览器无法读取位置。",
    "geo.timeout": "尚未获得定位。在开阔天空下通常需要再等几秒。",
    "geo.unavailable": "无法读取位置。",
    "geo.privacy":
      "与项目一同保存在本设备上。不会单独发送到任何地方，除非你选择包含，否则不会出现在共享报告中。",
    "rp.title": "田野报告",
    "rp.build": "生成报告（PDF）",
    "rp.building": "正在准备报告…",
    "rp.hint": "将打开打印对话框——请选择“存储为 PDF”。",
    "rp.includeLocation": "包含发现地点坐标",
    "rp.failed": "无法准备报告。",
    "rp.h.recordedOn": "记录于",
    "rp.h.notes": "备注",
    "rp.h.photographs": "照片",
    "rp.h.original": "拍摄原图",
    "rp.h.enhanced": "处理后",
    "rp.h.processingNote":
      "处理后的颜色来自像素运算（decorrelation stretch 或 CLAHE），属假彩色，并非颜料或岩石的真实颜色。",
    "rp.h.location": "发现地点",
    "rp.h.coordinates": "坐标",
    "rp.h.accuracyLabel": "精度",
    "rp.h.altitude": "海拔",
    "rp.h.locationWithheld": "本报告已刻意省略坐标。",
    "rp.h.measurements": "测量",
    "rp.h.scaleReference": "比例尺参照",
    "rp.h.reading": "建议释读",
    "rp.h.script": "文字",
    "rp.h.direction": "行文方向",
    "rp.h.transliteration": "转写",
    "rp.h.proposedReading": "建议释读",
    "rp.h.meaning": "含义",
    "rp.h.uncertainties": "存疑之处",
    "rp.h.alternatives": "其他可能",
    "rp.h.machineCaveat": "这是机器建议，而非确立的释读。未经铭文学者核验，不得作为释读成果引用。",
    "rp.h.corrections": "记录者的更正",
    "rp.h.references": "参考来源",
    "rp.h.page": "由 Athar 生成。释读为机器建议，需专家复核。",
  },
};
