/**
 * Strings for the administrator "Extensions & Scripts" section in the four
 * supported languages. Merged into DICT by i18n-dict.ts; English is the
 * fallback for any missing key.
 */

export const EXT_DICT: Record<string, Record<string, string>> = {
  en: {
    "ext.title": "Extensions & Scripts",
    "ext.intro":
      "Install and manage tools for image enhancement, inscription analysis, document processing and 3D reconstruction. Nothing runs automatically: an imported extension is reviewed, tested, and only then enabled. Administrator sign-in is checked on the server for every action.",
    "ext.tab.installed": "Installed extensions",
    "ext.tab.add": "Add extension",
    "ext.tab.script": "Import script",
    "ext.tab.worker": "Connect external worker / API",
    "ext.tab.logs": "Execution logs",
    "ext.runtime.browser": "Runs in this browser",
    "ext.runtime.backend": "Server API integration",
    "ext.runtime.external_worker": "External worker on your computer",
    "ext.status.imported": "Imported",
    "ext.status.validated": "Validated",
    "ext.status.tested": "Tested",
    "ext.status.enabled": "Enabled",
    "ext.status.disabled": "Disabled",
    "ext.status.failed": "Failed",
    "ext.lifecycle": "Imported → Validated → Tested → Enabled / Disabled / Failed",
    "ext.field.version": "Version",
    "ext.field.purpose": "Purpose",
    "ext.field.source": "Source",
    "ext.field.license": "Licence",
    "ext.field.requirements": "Runtime requirements",
    "ext.field.inputs": "Accepts",
    "ext.field.outputs": "Produces",
    "ext.field.permissions": "Permissions",
    "ext.field.surfaces": "Available on",
    "ext.field.config": "Configuration",
    "ext.field.endpoint": "Endpoint",
    "ext.paid": "Needs a paid service, hosting or hardware",
    "ext.free": "Free and open source",
    "ext.unavailable": "Unavailable — no processing worker is connected",
    "ext.available": "Worker connected",
    "ext.action.test": "Test on sample",
    "ext.action.enable": "Enable",
    "ext.action.disable": "Disable",
    "ext.action.update": "Update",
    "ext.action.rollback": "Roll back",
    "ext.action.remove": "Remove",
    "ext.action.review": "Review source",
    "ext.testing": "Testing…",
    "ext.testPassed": "Test passed in {ms} ms. This extension really processed the sample image.",
    "ext.testFailed": "Test failed: {error}",
    "ext.testUnavailable":
      "This runtime cannot be tested from the browser. It is shown as unavailable until the external program or API actually connects.",
    "ext.enabled": "Extension enabled.",
    "ext.disabled": "Extension disabled.",
    "ext.removed": "Extension removed. Your projects and exported results are untouched.",
    "ext.removeKeep": "Removing an extension keeps existing projects and exported results.",
    "ext.rolledBack": "Rolled back to the previous version. Test it before enabling it.",
    "ext.add.manifest": "Manifest (JSON)",
    "ext.add.module": "JavaScript module (optional, browser extensions only)",
    "ext.add.secret": "Server secret name (backend integrations)",
    "ext.add.submit": "Import for review",
    "ext.add.note":
      "The manifest is validated and the code is stored for your review. It is never run on the server, never given your session, your private files or any secret, and never uses eval or the application context.",
    "ext.add.contract":
      "Contract version 1: accepted input types, parameters, progress events, output types, error messages, required permissions and runtime.",
    "ext.source.name": "Name",
    "ext.source.url": "Source URL (e.g. GitHub)",
    "ext.source.purpose": "Purpose",
    "ext.source.license": "Licence",
    "ext.source.requirements": "Requirements",
    "ext.source.endpoint": "Endpoint (backend and external worker)",
    "ext.source.runtime": "Where does it really run?",
    "ext.source.paid": "Needs a paid service",
    "ext.source.submit": "Register source for review",
    "ext.source.note":
      "A URL only registers a source for review. No code is downloaded or executed. Python programs, GPU software and arbitrary repositories cannot run in a browser — they need a computer or a server you control.",
    "ext.worker.note":
      "Meshroom is registered as an external worker. It processes photographs on your own computer, not in the browser and not in a server function, and stays unavailable until that worker connects.",
    "ext.logs.empty": "No extension activity recorded yet.",
    "ext.logs.note": "Secrets and tokens are redacted before a log line is stored.",
    "ext.sandbox":
      "Browser extensions run in an isolated worker with no network, no storage and no access to your session; they receive only the file chosen for that run, with a time limit and a cancel button.",
    "ext.savedSeparately":
      "Originals are always preserved. A processed result is saved separately with the extension version and the settings used.",
    "ext.refresh": "Refresh",
    "ext.invalid": "Refused: {errors}",
    "ext.badJson": "That is not valid JSON.",
  },
  ar: {
    "ext.title": "الإضافات والسكربتات",
    "ext.intro":
      "تثبيت وإدارة أدوات تحسين الصور وتحليل النقوش ومعالجة المستندات وإعادة البناء ثلاثي الأبعاد. لا شيء يعمل تلقائيًا: تُراجع الإضافة المستوردة وتُختبر، ثم تُفعّل. تُتحقق صلاحية المسؤول في الخادم لكل إجراء.",
    "ext.tab.installed": "الإضافات المثبتة",
    "ext.tab.add": "إضافة جديدة",
    "ext.tab.script": "استيراد سكربت",
    "ext.tab.worker": "ربط عامل خارجي / واجهة برمجية",
    "ext.tab.logs": "سجلات التشغيل",
    "ext.runtime.browser": "تعمل في هذا المتصفح",
    "ext.runtime.backend": "تكامل مع واجهة برمجية في الخادم",
    "ext.runtime.external_worker": "عامل خارجي على كمبيوترك",
    "ext.status.imported": "مستوردة",
    "ext.status.validated": "تم التحقق منها",
    "ext.status.tested": "مُختبرة",
    "ext.status.enabled": "مُفعّلة",
    "ext.status.disabled": "مُعطّلة",
    "ext.status.failed": "فاشلة",
    "ext.lifecycle": "مستوردة → متحقق منها → مُختبرة → مُفعّلة / مُعطّلة / فاشلة",
    "ext.field.version": "الإصدار",
    "ext.field.purpose": "الغرض",
    "ext.field.source": "المصدر",
    "ext.field.license": "الترخيص",
    "ext.field.requirements": "متطلبات التشغيل",
    "ext.field.inputs": "تقبل",
    "ext.field.outputs": "تُخرج",
    "ext.field.permissions": "الصلاحيات",
    "ext.field.surfaces": "متاحة في",
    "ext.field.config": "الإعداد",
    "ext.field.endpoint": "العنوان",
    "ext.paid": "تحتاج خدمة مدفوعة أو استضافة أو عتادًا",
    "ext.free": "مجانية ومفتوحة المصدر",
    "ext.unavailable": "غير متاحة — لا يوجد كمبيوتر معالجة متصل",
    "ext.available": "كمبيوتر المعالجة متصل",
    "ext.action.test": "اختبار على نموذج",
    "ext.action.enable": "تفعيل",
    "ext.action.disable": "تعطيل",
    "ext.action.update": "تحديث",
    "ext.action.rollback": "رجوع للإصدار السابق",
    "ext.action.remove": "إزالة",
    "ext.action.review": "مراجعة المصدر",
    "ext.testing": "جارٍ الاختبار…",
    "ext.testPassed": "نجح الاختبار في {ms} مللي ثانية. عالجت الإضافة صورة النموذج فعليًا.",
    "ext.testFailed": "فشل الاختبار: {error}",
    "ext.testUnavailable":
      "لا يمكن اختبار هذا النوع من المتصفح. تظل غير متاحة حتى يتصل البرنامج الخارجي أو الواجهة البرمجية فعليًا.",
    "ext.enabled": "تم تفعيل الإضافة.",
    "ext.disabled": "تم تعطيل الإضافة.",
    "ext.removed": "أُزيلت الإضافة. مشاريعك ونتائجك المصدَّرة كما هي.",
    "ext.removeKeep": "إزالة الإضافة تُبقي المشاريع والنتائج المصدَّرة الموجودة.",
    "ext.rolledBack": "تم الرجوع إلى الإصدار السابق. اختبره قبل التفعيل.",
    "ext.add.manifest": "ملف الوصف (JSON)",
    "ext.add.module": "وحدة JavaScript (اختيارية، لإضافات المتصفح فقط)",
    "ext.add.secret": "اسم السر في الخادم (لتكاملات الواجهات البرمجية)",
    "ext.add.submit": "استيراد للمراجعة",
    "ext.add.note":
      "يُتحقق من ملف الوصف ويُخزَّن الكود لمراجعتك. لا يُشغَّل في الخادم، ولا يُمنح جلستك أو ملفاتك الخاصة أو أي سر، ولا يُستخدم eval ولا سياق التطبيق.",
    "ext.add.contract":
      "الإصدار 1 من العقد: أنواع المدخلات المقبولة، والمعاملات، وأحداث التقدم، وأنواع المخرجات، ورسائل الأخطاء، والصلاحيات وبيئة التشغيل المطلوبة.",
    "ext.source.name": "الاسم",
    "ext.source.url": "رابط المصدر (مثل GitHub)",
    "ext.source.purpose": "الغرض",
    "ext.source.license": "الترخيص",
    "ext.source.requirements": "المتطلبات",
    "ext.source.endpoint": "العنوان (للخادم والعامل الخارجي)",
    "ext.source.runtime": "أين تعمل فعليًا؟",
    "ext.source.paid": "تحتاج خدمة مدفوعة",
    "ext.source.submit": "تسجيل المصدر للمراجعة",
    "ext.source.note":
      "الرابط يسجّل مصدرًا للمراجعة فقط، ولا يُنزَّل أي كود ولا يُشغَّل. برامج Python وبرامج كرت الرسوم والمستودعات العامة لا تعمل داخل المتصفح؛ تحتاج كمبيوترًا أو خادمًا تملكه.",
    "ext.worker.note":
      "Meshroom مسجَّل كعامل خارجي. يعالج الصور على كمبيوترك، لا في المتصفح ولا في دوال الخادم، ويظل غير متاح حتى يتصل ذلك العامل.",
    "ext.logs.empty": "لا يوجد نشاط مسجَّل للإضافات بعد.",
    "ext.logs.note": "تُحجب الأسرار والرموز قبل تسجيل أي سطر.",
    "ext.sandbox":
      "إضافات المتصفح تعمل في عامل معزول بلا شبكة ولا تخزين ولا وصول إلى جلستك؛ تتلقى فقط الملف المختار لتلك العملية، مع حد زمني وزر إلغاء.",
    "ext.savedSeparately":
      "تُحفظ الصور الأصلية دائمًا. وتُحفظ النتيجة المعالجة بشكل منفصل مع إصدار الإضافة والإعدادات المستخدمة.",
    "ext.refresh": "تحديث",
    "ext.invalid": "مرفوض: {errors}",
    "ext.badJson": "هذا ليس JSON صالحًا.",
  },
  zh: {
    "ext.title": "扩展与脚本",
    "ext.intro":
      "安装并管理用于图像增强、铭文分析、文档处理和三维重建的工具。任何扩展都不会自动运行：导入后先审核、再测试，然后才能启用。每个操作都在服务器端校验管理员身份。",
    "ext.tab.installed": "已安装的扩展",
    "ext.tab.add": "添加扩展",
    "ext.tab.script": "导入脚本",
    "ext.tab.worker": "连接外部工作程序 / API",
    "ext.tab.logs": "运行日志",
    "ext.runtime.browser": "在本浏览器中运行",
    "ext.runtime.backend": "服务器 API 集成",
    "ext.runtime.external_worker": "在你的电脑上运行的外部程序",
    "ext.status.imported": "已导入",
    "ext.status.validated": "已校验",
    "ext.status.tested": "已测试",
    "ext.status.enabled": "已启用",
    "ext.status.disabled": "已停用",
    "ext.status.failed": "失败",
    "ext.lifecycle": "已导入 → 已校验 → 已测试 → 启用 / 停用 / 失败",
    "ext.field.version": "版本",
    "ext.field.purpose": "用途",
    "ext.field.source": "来源",
    "ext.field.license": "许可协议",
    "ext.field.requirements": "运行要求",
    "ext.field.inputs": "接受",
    "ext.field.outputs": "输出",
    "ext.field.permissions": "权限",
    "ext.field.surfaces": "可用于",
    "ext.field.config": "配置",
    "ext.field.endpoint": "接口地址",
    "ext.paid": "需要付费服务、托管或硬件",
    "ext.free": "免费开源",
    "ext.unavailable": "不可用 — 没有已连接的处理程序",
    "ext.available": "处理程序已连接",
    "ext.action.test": "用样例测试",
    "ext.action.enable": "启用",
    "ext.action.disable": "停用",
    "ext.action.update": "更新",
    "ext.action.rollback": "回滚",
    "ext.action.remove": "移除",
    "ext.action.review": "审核来源",
    "ext.testing": "测试中…",
    "ext.testPassed": "测试通过，用时 {ms} 毫秒。该扩展确实处理了样例图像。",
    "ext.testFailed": "测试失败：{error}",
    "ext.testUnavailable":
      "这种运行方式无法在浏览器中测试。在外部程序或 API 真正连接之前，它显示为不可用。",
    "ext.enabled": "扩展已启用。",
    "ext.disabled": "扩展已停用。",
    "ext.removed": "扩展已移除。你的项目和导出结果不受影响。",
    "ext.removeKeep": "移除扩展会保留现有项目和导出结果。",
    "ext.rolledBack": "已回滚到上一个版本。启用前请先测试。",
    "ext.add.manifest": "清单（JSON）",
    "ext.add.module": "JavaScript 模块（可选，仅浏览器扩展）",
    "ext.add.secret": "服务器密钥名称（后端集成）",
    "ext.add.submit": "导入以供审核",
    "ext.add.note":
      "清单会被校验，代码会被保存以供你审核。它不会在服务器上运行，不会获得你的会话、私有文件或任何密钥，也不会使用 eval 或应用主上下文。",
    "ext.add.contract":
      "契约版本 1：接受的输入类型、参数、进度事件、输出类型、错误信息、所需权限与运行环境。",
    "ext.source.name": "名称",
    "ext.source.url": "来源网址（例如 GitHub）",
    "ext.source.purpose": "用途",
    "ext.source.license": "许可协议",
    "ext.source.requirements": "要求",
    "ext.source.endpoint": "接口地址（后端与外部程序）",
    "ext.source.runtime": "它实际在哪里运行？",
    "ext.source.paid": "需要付费服务",
    "ext.source.submit": "登记来源以供审核",
    "ext.source.note":
      "网址只会登记一个待审核的来源，不会下载或执行任何代码。Python 程序、GPU 软件和任意代码仓库无法在浏览器中运行，它们需要你自己的电脑或服务器。",
    "ext.worker.note":
      "Meshroom 登记为外部工作程序。它在你自己的电脑上处理照片，不在浏览器也不在服务器函数中运行，在该程序连接之前始终不可用。",
    "ext.logs.empty": "暂无扩展活动记录。",
    "ext.logs.note": "写入日志前会隐去密钥和令牌。",
    "ext.sandbox":
      "浏览器扩展在隔离的工作线程中运行，没有网络、没有存储、无法访问你的会话；每次运行只收到所选的那个文件，并有时间限制和取消按钮。",
    "ext.savedSeparately": "原始文件始终保留。处理结果单独保存，并记录扩展版本与所用设置。",
    "ext.refresh": "刷新",
    "ext.invalid": "已拒绝：{errors}",
    "ext.badJson": "这不是有效的 JSON。",
  },
  fr: {
    "ext.title": "Extensions et scripts",
    "ext.intro":
      "Installez et gérez des outils d’amélioration d’image, d’analyse d’inscriptions, de traitement de documents et de reconstruction 3D. Rien ne s’exécute automatiquement : une extension importée est examinée, testée, puis seulement activée. L’autorisation administrateur est vérifiée côté serveur pour chaque action.",
    "ext.tab.installed": "Extensions installées",
    "ext.tab.add": "Ajouter une extension",
    "ext.tab.script": "Importer un script",
    "ext.tab.worker": "Connecter un worker externe / une API",
    "ext.tab.logs": "Journaux d’exécution",
    "ext.runtime.browser": "S’exécute dans ce navigateur",
    "ext.runtime.backend": "Intégration d’API côté serveur",
    "ext.runtime.external_worker": "Programme externe sur votre ordinateur",
    "ext.status.imported": "Importée",
    "ext.status.validated": "Validée",
    "ext.status.tested": "Testée",
    "ext.status.enabled": "Activée",
    "ext.status.disabled": "Désactivée",
    "ext.status.failed": "Échec",
    "ext.lifecycle": "Importée → Validée → Testée → Activée / Désactivée / Échec",
    "ext.field.version": "Version",
    "ext.field.purpose": "Objet",
    "ext.field.source": "Source",
    "ext.field.license": "Licence",
    "ext.field.requirements": "Prérequis d’exécution",
    "ext.field.inputs": "Accepte",
    "ext.field.outputs": "Produit",
    "ext.field.permissions": "Autorisations",
    "ext.field.surfaces": "Disponible sur",
    "ext.field.config": "Configuration",
    "ext.field.endpoint": "Point d’accès",
    "ext.paid": "Nécessite un service payant, un hébergement ou du matériel",
    "ext.free": "Libre et open source",
    "ext.unavailable": "Indisponible — aucun ordinateur de traitement connecté",
    "ext.available": "Ordinateur de traitement connecté",
    "ext.action.test": "Tester sur un échantillon",
    "ext.action.enable": "Activer",
    "ext.action.disable": "Désactiver",
    "ext.action.update": "Mettre à jour",
    "ext.action.rollback": "Revenir en arrière",
    "ext.action.remove": "Supprimer",
    "ext.action.review": "Examiner la source",
    "ext.testing": "Test en cours…",
    "ext.testPassed":
      "Test réussi en {ms} ms. L’extension a réellement traité l’image d’échantillon.",
    "ext.testFailed": "Échec du test : {error}",
    "ext.testUnavailable":
      "Ce mode d’exécution ne peut pas être testé depuis le navigateur. Il reste indisponible tant que le programme externe ou l’API ne se connecte pas réellement.",
    "ext.enabled": "Extension activée.",
    "ext.disabled": "Extension désactivée.",
    "ext.removed": "Extension supprimée. Vos projets et résultats exportés sont intacts.",
    "ext.removeKeep": "Supprimer une extension conserve les projets et les résultats exportés.",
    "ext.rolledBack": "Retour à la version précédente. Testez-la avant de l’activer.",
    "ext.add.manifest": "Manifeste (JSON)",
    "ext.add.module": "Module JavaScript (facultatif, extensions navigateur uniquement)",
    "ext.add.secret": "Nom du secret serveur (intégrations d’API)",
    "ext.add.submit": "Importer pour examen",
    "ext.add.note":
      "Le manifeste est validé et le code est conservé pour votre examen. Il n’est jamais exécuté sur le serveur, ne reçoit ni votre session, ni vos fichiers privés, ni aucun secret, et n’utilise ni eval ni le contexte de l’application.",
    "ext.add.contract":
      "Contrat version 1 : types d’entrée acceptés, paramètres, événements de progression, types de sortie, messages d’erreur, autorisations et environnement requis.",
    "ext.source.name": "Nom",
    "ext.source.url": "URL de la source (par ex. GitHub)",
    "ext.source.purpose": "Objet",
    "ext.source.license": "Licence",
    "ext.source.requirements": "Prérequis",
    "ext.source.endpoint": "Point d’accès (serveur et worker externe)",
    "ext.source.runtime": "Où s’exécute-t-elle réellement ?",
    "ext.source.paid": "Nécessite un service payant",
    "ext.source.submit": "Enregistrer la source pour examen",
    "ext.source.note":
      "Une URL enregistre seulement une source à examiner. Aucun code n’est téléchargé ni exécuté. Les programmes Python, les logiciels GPU et les dépôts quelconques ne peuvent pas s’exécuter dans un navigateur : ils exigent un ordinateur ou un serveur que vous contrôlez.",
    "ext.worker.note":
      "Meshroom est enregistré comme worker externe. Il traite les photographies sur votre propre ordinateur, jamais dans le navigateur ni dans une fonction serveur, et reste indisponible tant que ce worker n’est pas connecté.",
    "ext.logs.empty": "Aucune activité d’extension enregistrée pour l’instant.",
    "ext.logs.note": "Les secrets et jetons sont masqués avant l’écriture d’une ligne de journal.",
    "ext.sandbox":
      "Les extensions navigateur s’exécutent dans un worker isolé, sans réseau, sans stockage et sans accès à votre session ; elles ne reçoivent que le fichier choisi pour cette exécution, avec une limite de temps et un bouton d’annulation.",
    "ext.savedSeparately":
      "Les originaux sont toujours conservés. Un résultat traité est enregistré séparément avec la version de l’extension et les réglages utilisés.",
    "ext.refresh": "Actualiser",
    "ext.invalid": "Refusé : {errors}",
    "ext.badJson": "Ce n’est pas du JSON valide.",
  },
};
