/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApiAccessRouteImport } from './routes/api/access'
import { Route as ApiAccountRouteImport } from './routes/api/account'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiAskRouteImport } from './routes/api/ask'
import { Route as ApiCorrectionsRouteImport } from './routes/api/corrections'
import { Route as ApiFeedbackRouteImport } from './routes/api/feedback'
import { Route as ApiAdminAccessRouteImport } from './routes/api/admin/access'
import { Route as ApiAdminAiRouteImport } from './routes/api/admin/ai'
import { Route as ApiAdminCorrectionsRouteImport } from './routes/api/admin/corrections'
import { Route as ApiAdminExtensionsRouteImport } from './routes/api/admin/extensions'
import { Route as ApiAdminFeedbackRouteImport } from './routes/api/admin/feedback'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminResearchRouteImport } from './routes/api/admin/research'
import { Route as ApiAdminWorkerRouteImport } from './routes/api/admin/worker'
import { Route as ApiCorpusImageRouteImport } from './routes/api/corpus/image'
import { Route as ApiCorpusImagesRouteImport } from './routes/api/corpus/images'
import { Route as ApiGlyphsDatasetRouteImport } from './routes/api/glyphs/dataset'
import { Route as ApiGlyphsExemplarsRouteImport } from './routes/api/glyphs/exemplars'
import { Route as ApiGlyphsLabelRouteImport } from './routes/api/glyphs/label'
import { Route as ApiGlyphsModelRouteImport } from './routes/api/glyphs/model'
import { Route as ApiPublicWorkerRouteImport } from './routes/api/public/worker'
import { Route as ApiReferencesLookupRouteImport } from './routes/api/references/lookup'
import { Route as ApiReferencesStatusRouteImport } from './routes/api/references/status'
import { Route as ApiThreeDJobsRouteImport } from './routes/api/three-d/jobs'
import { Route as ApiAdminCorpusManageRouteImport } from './routes/api/admin/corpus/manage'
import { Route as ApiAdminGlyphsReviewRouteImport } from './routes/api/admin/glyphs/review'
import { Route as ApiAdminGlyphsTrainRouteImport } from './routes/api/admin/glyphs/train'
import { Route as ApiAdminReferencesImportRouteImport } from './routes/api/admin/references/import'
import { Route as ApiThreeDStatusIdRouteImport } from './routes/api/three-d/status.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccessRoute = ApiAccessRouteImport.update({
  id: '/api/access',
  path: '/api/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountRoute = ApiAccountRouteImport.update({
  id: '/api/account',
  path: '/api/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCorrectionsRoute = ApiCorrectionsRouteImport.update({
  id: '/api/corrections',
  path: '/api/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAccessRoute = ApiAdminAccessRouteImport.update({
  id: '/api/admin/access',
  path: '/api/admin/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAiRoute = ApiAdminAiRouteImport.update({
  id: '/api/admin/ai',
  path: '/api/admin/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCorrectionsRoute = ApiAdminCorrectionsRouteImport.update({
  id: '/api/admin/corrections',
  path: '/api/admin/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminExtensionsRoute = ApiAdminExtensionsRouteImport.update({
  id: '/api/admin/extensions',
  path: '/api/admin/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFeedbackRoute = ApiAdminFeedbackRouteImport.update({
  id: '/api/admin/feedback',
  path: '/api/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResearchRoute = ApiAdminResearchRouteImport.update({
  id: '/api/admin/research',
  path: '/api/admin/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminWorkerRoute = ApiAdminWorkerRouteImport.update({
  id: '/api/admin/worker',
  path: '/api/admin/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCorpusImageRoute = ApiCorpusImageRouteImport.update({
  id: '/api/corpus/image',
  path: '/api/corpus/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCorpusImagesRoute = ApiCorpusImagesRouteImport.update({
  id: '/api/corpus/images',
  path: '/api/corpus/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGlyphsDatasetRoute = ApiGlyphsDatasetRouteImport.update({
  id: '/api/glyphs/dataset',
  path: '/api/glyphs/dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGlyphsExemplarsRoute = ApiGlyphsExemplarsRouteImport.update({
  id: '/api/glyphs/exemplars',
  path: '/api/glyphs/exemplars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGlyphsLabelRoute = ApiGlyphsLabelRouteImport.update({
  id: '/api/glyphs/label',
  path: '/api/glyphs/label',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGlyphsModelRoute = ApiGlyphsModelRouteImport.update({
  id: '/api/glyphs/model',
  path: '/api/glyphs/model',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkerRoute = ApiPublicWorkerRouteImport.update({
  id: '/api/public/worker',
  path: '/api/public/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferencesLookupRoute = ApiReferencesLookupRouteImport.update({
  id: '/api/references/lookup',
  path: '/api/references/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferencesStatusRoute = ApiReferencesStatusRouteImport.update({
  id: '/api/references/status',
  path: '/api/references/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThreeDJobsRoute = ApiThreeDJobsRouteImport.update({
  id: '/api/three-d/jobs',
  path: '/api/three-d/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCorpusManageRoute = ApiAdminCorpusManageRouteImport.update({
  id: '/api/admin/corpus/manage',
  path: '/api/admin/corpus/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGlyphsReviewRoute = ApiAdminGlyphsReviewRouteImport.update({
  id: '/api/admin/glyphs/review',
  path: '/api/admin/glyphs/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGlyphsTrainRoute = ApiAdminGlyphsTrainRouteImport.update({
  id: '/api/admin/glyphs/train',
  path: '/api/admin/glyphs/train',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReferencesImportRoute =
  ApiAdminReferencesImportRouteImport.update({
    id: '/api/admin/references/import',
    path: '/api/admin/references/import',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiThreeDStatusIdRoute = ApiThreeDStatusIdRouteImport.update({
  id: '/api/three-d/status/$id',
  path: '/api/three-d/status/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/access': typeof ApiAccessRoute
  '/api/account': typeof ApiAccountRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/ask': typeof ApiAskRoute
  '/api/corrections': typeof ApiCorrectionsRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/admin/access': typeof ApiAdminAccessRoute
  '/api/admin/ai': typeof ApiAdminAiRoute
  '/api/admin/corrections': typeof ApiAdminCorrectionsRoute
  '/api/admin/extensions': typeof ApiAdminExtensionsRoute
  '/api/admin/feedback': typeof ApiAdminFeedbackRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/research': typeof ApiAdminResearchRoute
  '/api/admin/worker': typeof ApiAdminWorkerRoute
  '/api/corpus/image': typeof ApiCorpusImageRoute
  '/api/corpus/images': typeof ApiCorpusImagesRoute
  '/api/glyphs/dataset': typeof ApiGlyphsDatasetRoute
  '/api/glyphs/exemplars': typeof ApiGlyphsExemplarsRoute
  '/api/glyphs/label': typeof ApiGlyphsLabelRoute
  '/api/glyphs/model': typeof ApiGlyphsModelRoute
  '/api/public/worker': typeof ApiPublicWorkerRoute
  '/api/references/lookup': typeof ApiReferencesLookupRoute
  '/api/references/status': typeof ApiReferencesStatusRoute
  '/api/three-d/jobs': typeof ApiThreeDJobsRoute
  '/api/admin/corpus/manage': typeof ApiAdminCorpusManageRoute
  '/api/admin/glyphs/review': typeof ApiAdminGlyphsReviewRoute
  '/api/admin/glyphs/train': typeof ApiAdminGlyphsTrainRoute
  '/api/admin/references/import': typeof ApiAdminReferencesImportRoute
  '/api/three-d/status/$id': typeof ApiThreeDStatusIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/access': typeof ApiAccessRoute
  '/api/account': typeof ApiAccountRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/ask': typeof ApiAskRoute
  '/api/corrections': typeof ApiCorrectionsRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/admin/access': typeof ApiAdminAccessRoute
  '/api/admin/ai': typeof ApiAdminAiRoute
  '/api/admin/corrections': typeof ApiAdminCorrectionsRoute
  '/api/admin/extensions': typeof ApiAdminExtensionsRoute
  '/api/admin/feedback': typeof ApiAdminFeedbackRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/research': typeof ApiAdminResearchRoute
  '/api/admin/worker': typeof ApiAdminWorkerRoute
  '/api/corpus/image': typeof ApiCorpusImageRoute
  '/api/corpus/images': typeof ApiCorpusImagesRoute
  '/api/glyphs/dataset': typeof ApiGlyphsDatasetRoute
  '/api/glyphs/exemplars': typeof ApiGlyphsExemplarsRoute
  '/api/glyphs/label': typeof ApiGlyphsLabelRoute
  '/api/glyphs/model': typeof ApiGlyphsModelRoute
  '/api/public/worker': typeof ApiPublicWorkerRoute
  '/api/references/lookup': typeof ApiReferencesLookupRoute
  '/api/references/status': typeof ApiReferencesStatusRoute
  '/api/three-d/jobs': typeof ApiThreeDJobsRoute
  '/api/admin/corpus/manage': typeof ApiAdminCorpusManageRoute
  '/api/admin/glyphs/review': typeof ApiAdminGlyphsReviewRoute
  '/api/admin/glyphs/train': typeof ApiAdminGlyphsTrainRoute
  '/api/admin/references/import': typeof ApiAdminReferencesImportRoute
  '/api/three-d/status/$id': typeof ApiThreeDStatusIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/access': typeof ApiAccessRoute
  '/api/account': typeof ApiAccountRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/ask': typeof ApiAskRoute
  '/api/corrections': typeof ApiCorrectionsRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/admin/access': typeof ApiAdminAccessRoute
  '/api/admin/ai': typeof ApiAdminAiRoute
  '/api/admin/corrections': typeof ApiAdminCorrectionsRoute
  '/api/admin/extensions': typeof ApiAdminExtensionsRoute
  '/api/admin/feedback': typeof ApiAdminFeedbackRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/research': typeof ApiAdminResearchRoute
  '/api/admin/worker': typeof ApiAdminWorkerRoute
  '/api/corpus/image': typeof ApiCorpusImageRoute
  '/api/corpus/images': typeof ApiCorpusImagesRoute
  '/api/glyphs/dataset': typeof ApiGlyphsDatasetRoute
  '/api/glyphs/exemplars': typeof ApiGlyphsExemplarsRoute
  '/api/glyphs/label': typeof ApiGlyphsLabelRoute
  '/api/glyphs/model': typeof ApiGlyphsModelRoute
  '/api/public/worker': typeof ApiPublicWorkerRoute
  '/api/references/lookup': typeof ApiReferencesLookupRoute
  '/api/references/status': typeof ApiReferencesStatusRoute
  '/api/three-d/jobs': typeof ApiThreeDJobsRoute
  '/api/admin/corpus/manage': typeof ApiAdminCorpusManageRoute
  '/api/admin/glyphs/review': typeof ApiAdminGlyphsReviewRoute
  '/api/admin/glyphs/train': typeof ApiAdminGlyphsTrainRoute
  '/api/admin/references/import': typeof ApiAdminReferencesImportRoute
  '/api/three-d/status/$id': typeof ApiThreeDStatusIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/access'
    | '/api/account'
    | '/api/analyze'
    | '/api/ask'
    | '/api/corrections'
    | '/api/feedback'
    | '/api/admin/access'
    | '/api/admin/ai'
    | '/api/admin/corrections'
    | '/api/admin/extensions'
    | '/api/admin/feedback'
    | '/api/admin/login'
    | '/api/admin/research'
    | '/api/admin/worker'
    | '/api/corpus/image'
    | '/api/corpus/images'
    | '/api/glyphs/dataset'
    | '/api/glyphs/exemplars'
    | '/api/glyphs/label'
    | '/api/glyphs/model'
    | '/api/public/worker'
    | '/api/references/lookup'
    | '/api/references/status'
    | '/api/three-d/jobs'
    | '/api/admin/corpus/manage'
    | '/api/admin/glyphs/review'
    | '/api/admin/glyphs/train'
    | '/api/admin/references/import'
    | '/api/three-d/status/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/access'
    | '/api/account'
    | '/api/analyze'
    | '/api/ask'
    | '/api/corrections'
    | '/api/feedback'
    | '/api/admin/access'
    | '/api/admin/ai'
    | '/api/admin/corrections'
    | '/api/admin/extensions'
    | '/api/admin/feedback'
    | '/api/admin/login'
    | '/api/admin/research'
    | '/api/admin/worker'
    | '/api/corpus/image'
    | '/api/corpus/images'
    | '/api/glyphs/dataset'
    | '/api/glyphs/exemplars'
    | '/api/glyphs/label'
    | '/api/glyphs/model'
    | '/api/public/worker'
    | '/api/references/lookup'
    | '/api/references/status'
    | '/api/three-d/jobs'
    | '/api/admin/corpus/manage'
    | '/api/admin/glyphs/review'
    | '/api/admin/glyphs/train'
    | '/api/admin/references/import'
    | '/api/three-d/status/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/access'
    | '/api/account'
    | '/api/analyze'
    | '/api/ask'
    | '/api/corrections'
    | '/api/feedback'
    | '/api/admin/access'
    | '/api/admin/ai'
    | '/api/admin/corrections'
    | '/api/admin/extensions'
    | '/api/admin/feedback'
    | '/api/admin/login'
    | '/api/admin/research'
    | '/api/admin/worker'
    | '/api/corpus/image'
    | '/api/corpus/images'
    | '/api/glyphs/dataset'
    | '/api/glyphs/exemplars'
    | '/api/glyphs/label'
    | '/api/glyphs/model'
    | '/api/public/worker'
    | '/api/references/lookup'
    | '/api/references/status'
    | '/api/three-d/jobs'
    | '/api/admin/corpus/manage'
    | '/api/admin/glyphs/review'
    | '/api/admin/glyphs/train'
    | '/api/admin/references/import'
    | '/api/three-d/status/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiAccessRoute: typeof ApiAccessRoute
  ApiAccountRoute: typeof ApiAccountRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiCorrectionsRoute: typeof ApiCorrectionsRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiAdminAccessRoute: typeof ApiAdminAccessRoute
  ApiAdminAiRoute: typeof ApiAdminAiRoute
  ApiAdminCorrectionsRoute: typeof ApiAdminCorrectionsRoute
  ApiAdminExtensionsRoute: typeof ApiAdminExtensionsRoute
  ApiAdminFeedbackRoute: typeof ApiAdminFeedbackRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminResearchRoute: typeof ApiAdminResearchRoute
  ApiAdminWorkerRoute: typeof ApiAdminWorkerRoute
  ApiCorpusImageRoute: typeof ApiCorpusImageRoute
  ApiCorpusImagesRoute: typeof ApiCorpusImagesRoute
  ApiGlyphsDatasetRoute: typeof ApiGlyphsDatasetRoute
  ApiGlyphsExemplarsRoute: typeof ApiGlyphsExemplarsRoute
  ApiGlyphsLabelRoute: typeof ApiGlyphsLabelRoute
  ApiGlyphsModelRoute: typeof ApiGlyphsModelRoute
  ApiPublicWorkerRoute: typeof ApiPublicWorkerRoute
  ApiReferencesLookupRoute: typeof ApiReferencesLookupRoute
  ApiReferencesStatusRoute: typeof ApiReferencesStatusRoute
  ApiThreeDJobsRoute: typeof ApiThreeDJobsRoute
  ApiAdminCorpusManageRoute: typeof ApiAdminCorpusManageRoute
  ApiAdminGlyphsReviewRoute: typeof ApiAdminGlyphsReviewRoute
  ApiAdminGlyphsTrainRoute: typeof ApiAdminGlyphsTrainRoute
  ApiAdminReferencesImportRoute: typeof ApiAdminReferencesImportRoute
  ApiThreeDStatusIdRoute: typeof ApiThreeDStatusIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/access': {
      id: '/api/access'
      path: '/api/access'
      fullPath: '/api/access'
      preLoaderRoute: typeof ApiAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account': {
      id: '/api/account'
      path: '/api/account'
      fullPath: '/api/account'
      preLoaderRoute: typeof ApiAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/corrections': {
      id: '/api/corrections'
      path: '/api/corrections'
      fullPath: '/api/corrections'
      preLoaderRoute: typeof ApiCorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/access': {
      id: '/api/admin/access'
      path: '/api/admin/access'
      fullPath: '/api/admin/access'
      preLoaderRoute: typeof ApiAdminAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ai': {
      id: '/api/admin/ai'
      path: '/api/admin/ai'
      fullPath: '/api/admin/ai'
      preLoaderRoute: typeof ApiAdminAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/corrections': {
      id: '/api/admin/corrections'
      path: '/api/admin/corrections'
      fullPath: '/api/admin/corrections'
      preLoaderRoute: typeof ApiAdminCorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/extensions': {
      id: '/api/admin/extensions'
      path: '/api/admin/extensions'
      fullPath: '/api/admin/extensions'
      preLoaderRoute: typeof ApiAdminExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/feedback': {
      id: '/api/admin/feedback'
      path: '/api/admin/feedback'
      fullPath: '/api/admin/feedback'
      preLoaderRoute: typeof ApiAdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/research': {
      id: '/api/admin/research'
      path: '/api/admin/research'
      fullPath: '/api/admin/research'
      preLoaderRoute: typeof ApiAdminResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/worker': {
      id: '/api/admin/worker'
      path: '/api/admin/worker'
      fullPath: '/api/admin/worker'
      preLoaderRoute: typeof ApiAdminWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/corpus/image': {
      id: '/api/corpus/image'
      path: '/api/corpus/image'
      fullPath: '/api/corpus/image'
      preLoaderRoute: typeof ApiCorpusImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/corpus/images': {
      id: '/api/corpus/images'
      path: '/api/corpus/images'
      fullPath: '/api/corpus/images'
      preLoaderRoute: typeof ApiCorpusImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/glyphs/dataset': {
      id: '/api/glyphs/dataset'
      path: '/api/glyphs/dataset'
      fullPath: '/api/glyphs/dataset'
      preLoaderRoute: typeof ApiGlyphsDatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/glyphs/exemplars': {
      id: '/api/glyphs/exemplars'
      path: '/api/glyphs/exemplars'
      fullPath: '/api/glyphs/exemplars'
      preLoaderRoute: typeof ApiGlyphsExemplarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/glyphs/label': {
      id: '/api/glyphs/label'
      path: '/api/glyphs/label'
      fullPath: '/api/glyphs/label'
      preLoaderRoute: typeof ApiGlyphsLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/glyphs/model': {
      id: '/api/glyphs/model'
      path: '/api/glyphs/model'
      fullPath: '/api/glyphs/model'
      preLoaderRoute: typeof ApiGlyphsModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker': {
      id: '/api/public/worker'
      path: '/api/public/worker'
      fullPath: '/api/public/worker'
      preLoaderRoute: typeof ApiPublicWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/references/lookup': {
      id: '/api/references/lookup'
      path: '/api/references/lookup'
      fullPath: '/api/references/lookup'
      preLoaderRoute: typeof ApiReferencesLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/references/status': {
      id: '/api/references/status'
      path: '/api/references/status'
      fullPath: '/api/references/status'
      preLoaderRoute: typeof ApiReferencesStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/three-d/jobs': {
      id: '/api/three-d/jobs'
      path: '/api/three-d/jobs'
      fullPath: '/api/three-d/jobs'
      preLoaderRoute: typeof ApiThreeDJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/corpus/manage': {
      id: '/api/admin/corpus/manage'
      path: '/api/admin/corpus/manage'
      fullPath: '/api/admin/corpus/manage'
      preLoaderRoute: typeof ApiAdminCorpusManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/glyphs/review': {
      id: '/api/admin/glyphs/review'
      path: '/api/admin/glyphs/review'
      fullPath: '/api/admin/glyphs/review'
      preLoaderRoute: typeof ApiAdminGlyphsReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/glyphs/train': {
      id: '/api/admin/glyphs/train'
      path: '/api/admin/glyphs/train'
      fullPath: '/api/admin/glyphs/train'
      preLoaderRoute: typeof ApiAdminGlyphsTrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/references/import': {
      id: '/api/admin/references/import'
      path: '/api/admin/references/import'
      fullPath: '/api/admin/references/import'
      preLoaderRoute: typeof ApiAdminReferencesImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/three-d/status/$id': {
      id: '/api/three-d/status/$id'
      path: '/api/three-d/status/$id'
      fullPath: '/api/three-d/status/$id'
      preLoaderRoute: typeof ApiThreeDStatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiAccessRoute: ApiAccessRoute,
  ApiAccountRoute: ApiAccountRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiAskRoute: ApiAskRoute,
  ApiCorrectionsRoute: ApiCorrectionsRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiAdminAccessRoute: ApiAdminAccessRoute,
  ApiAdminAiRoute: ApiAdminAiRoute,
  ApiAdminCorrectionsRoute: ApiAdminCorrectionsRoute,
  ApiAdminExtensionsRoute: ApiAdminExtensionsRoute,
  ApiAdminFeedbackRoute: ApiAdminFeedbackRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminResearchRoute: ApiAdminResearchRoute,
  ApiAdminWorkerRoute: ApiAdminWorkerRoute,
  ApiCorpusImageRoute: ApiCorpusImageRoute,
  ApiCorpusImagesRoute: ApiCorpusImagesRoute,
  ApiGlyphsDatasetRoute: ApiGlyphsDatasetRoute,
  ApiGlyphsExemplarsRoute: ApiGlyphsExemplarsRoute,
  ApiGlyphsLabelRoute: ApiGlyphsLabelRoute,
  ApiGlyphsModelRoute: ApiGlyphsModelRoute,
  ApiPublicWorkerRoute: ApiPublicWorkerRoute,
  ApiReferencesLookupRoute: ApiReferencesLookupRoute,
  ApiReferencesStatusRoute: ApiReferencesStatusRoute,
  ApiThreeDJobsRoute: ApiThreeDJobsRoute,
  ApiAdminCorpusManageRoute: ApiAdminCorpusManageRoute,
  ApiAdminGlyphsReviewRoute: ApiAdminGlyphsReviewRoute,
  ApiAdminGlyphsTrainRoute: ApiAdminGlyphsTrainRoute,
  ApiAdminReferencesImportRoute: ApiAdminReferencesImportRoute,
  ApiThreeDStatusIdRoute: ApiThreeDStatusIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
