// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function isValidHttpUrl(url?: string | null): boolean {
  if (!url || typeof url !== "string") return false;
  const trimmed = url.trim();
  if (!/^https?:\/\//i.test(trimmed)) return false;
  try {
    const parsed = new URL(trimmed);
    return parsed.protocol === "http:" || parsed.protocol === "https:";
  } catch {
    return false;
  }
}

function isPlaceholder(url?: string | null, key?: string | null): boolean {
  if (!url || !key) return true;
  if (!isValidHttpUrl(url)) return true;
  if (url.includes("placeholder.supabase.co")) return true;
  if (key === "dummy-service-key" || key === "dummy-key" || key === "placeholder-service-key") {
    return true;
  }
  return false;
}

function createMockAdminClient() {
  const mockQueryBuilder = () => {
    const builder = {
      select: () => builder,
      insert: async () => ({ data: null, error: null }),
      update: async () => ({ data: null, error: null }),
      delete: async () => ({ data: null, error: null }),
      upsert: async () => ({ data: null, error: null }),
      eq: () => builder,
      neq: () => builder,
      gt: () => builder,
      lt: () => builder,
      gte: () => builder,
      lte: () => builder,
      like: () => builder,
      ilike: () => builder,
      is: () => builder,
      in: () => builder,
      order: () => builder,
      limit: () => builder,
      range: () => builder,
      single: async () => ({ data: null, error: null }),
      maybeSingle: async () => ({ data: null, error: null }),
      then: (onfulfilled?: (value: unknown) => unknown) =>
        Promise.resolve({ data: [], error: null }).then(onfulfilled),
    };
    return builder;
  };

  return {
    auth: {
      admin: {
        createUser: async () => ({ data: { user: null }, error: null }),
        deleteUser: async () => ({ data: null, error: null }),
        getUserById: async () => ({ data: { user: null }, error: null }),
        listUsers: async () => ({ data: { users: [] }, error: null }),
      },
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: null }),
    },
    from: () => mockQueryBuilder(),
    rpc: async () => ({ data: null, error: null }),
    storage: {
      from: () => ({
        upload: async () => ({ data: null, error: null }),
        download: async () => ({ data: null, error: null }),
        getPublicUrl: () => ({ data: { publicUrl: "" } }),
      }),
    },
  } as unknown as ReturnType<typeof createClient<Database>>;
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env["SUPABASE_URL"];
  const SUPABASE_SERVICE_ROLE_KEY = process.env["SUPABASE_SERVICE_ROLE_KEY"];

  const fallbackUrl = "https://placeholder.supabase.co";
  const fallbackKey = "dummy-service-key";
  const effectiveUrl = (isValidHttpUrl(SUPABASE_URL) ? SUPABASE_URL : fallbackUrl) as string;
  const effectiveKey = SUPABASE_SERVICE_ROLE_KEY || fallbackKey;

  if (isPlaceholder(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)) {
    return createMockAdminClient();
  }

  try {
    return createClient<Database>(effectiveUrl, effectiveKey, {
      global: {
        fetch: createSupabaseFetch(effectiveKey),
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });
  } catch (err) {
    console.warn(
      "[Supabase Admin] Failed to initialize admin client with provided credentials:",
      err,
    );
    return createMockAdminClient();
  }
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});

// إضافة مغلف أمان في استدعاءات Supabase السيرفرية
export async function safeDbQuery<T>(queryFn: () => Promise<T>, fallbackData: T): Promise<T> {
  const url = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  if (!url || url.includes("placeholder") || url.includes("disabled")) {
    return fallbackData; // إرجاع مصفوفة فارغة أو قيمة بديلة دون إسقاط السيرفر
  }
  try {
    return await queryFn();
  } catch (_e) {
    return fallbackData;
  }
}
